<li><a href="/">Home</a></li>
<li><a href="/about.php">About</a></li>
<li><a href="/tutorials.php">Tutorials</a></li>
<li><a href="/downloads.php">Downloads</a></li>
<li><a href="/games.php">Games</a></li>
<li><a href="/trips.php">Trips</a></li>
<li><a href="/signup.php">Sign Up</a></li>
<li><a href="/careers.php">Careers</a></li>
<li><a href="/calendar.php">Calendar</a></li>